services:

  mysql:
    image: mysql:8.4.8
    container_name: payflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - payflow-network

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: payflow-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - payflow-network

  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      RABBIT_HOST: rabbitmq
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - payflow-network

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      RABBIT_HOST: rabbitmq
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
    networks:
      - payflow-network

volumes:
  mysql_data:

networks:
  payflow-network:
    driver: bridge
