version: "3.9"

services:

  mysql:
    image: mysql:8.4.8
    container_name: payflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payflow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - payflow-network

volumes:
  mysql_data:

networks:
  payflow-network:
    driver: bridge
